<?php
get_header();
get_template_part('templates/components/header');
get_template_part('templates/pages/home/hero');
get_template_part('templates/pages/home/sobre');
get_template_part('templates/pages/home/beneficios');
get_template_part('templates/pages/home/citacoes');
get_template_part('templates/pages/home/faq');
get_template_part('templates/pages/home/contact');
get_template_part('templates/components/footer');
get_footer();
